### PR TITLE
add license (CC-BY-SA-4.0)

### PR DESCRIPTION
**Pull request by moedn**
solving #14 to make it open source :)

### CODE REVIEW

**Comment by timmwille** [comment]
CCBY might be better suited as we're not open sourcing all the documents out there based on this, right? keep it simple in this case :blush:

**Comment by moedn** [comment]
@timmwille Well, the license won't apply for documents created _with_ this template. Just when direct changes to the template are performed the ShareAlike comes into action.

However, we could also propose a weak-copyleft license (as `LGPL-3.0-or-later`) do be more specific about it

**Comment by benedictdudel** [comment]
I wanted to reach out to apologize for not merging your pull request. Unfortunately, I have had very limited free time lately and have not been able to give the project the attention it deserves. However, I have recently seen an increase in interest in the template and have decided to give the project another chance.

I understand that this may be disappointing, but I hope you can understand my decision. I really appreciate your contribution and willingness to help improve the template. I hope you will continue to contribute to the project in the future ❤️

**Comment by moedn** [comment]
hey man, all good :) emotional well-being goes first. good to have you back though! :)

it's an amazing template that already saved me so much time. happy to go further with this :+1:

**Pull request merged**
